### ISSUE TITLE
Listado de conjuntos de datos accesibles

### ISSUE THREAD

**Issue by bbaruque** [rnc0011/SistemaRecomendacionTFG#14]
Mejor incluir ya las referenicas en la documentación.

**Comment by rnc0011** [comment]
Los conjuntos de datos seleccionados (de momento) son:

- [Anime](https://www.kaggle.com/CooperUnion/anime-recommendations-database#rating.csv)

- [Last.FM](https://grouplens.org/datasets/hetrec-2011/)

- [Book-Crossing](http://www2.informatik.uni-freiburg.de/~cziegler/BX/)

También se usará el conjunto de MovieLens ya utilizado anteriormente; y puede que el conjunto de datos de la competición de [Trivago](http://www.recsyschallenge.com/2019/) en cuanto esté disponible.
