### ISSUE TITLE
Uniformizar salida de los modelos

### ISSUE THREAD

**Issue by bbaruque** [rnc0011/SistemaRecomendacionTFG#20]
Pensar la estructura común de un dataframe para la SALIDA de los diferentes modelos de recomendadores a probar.

Preparado para realizar el cálculo de las medidas buscadas.

**Comment by rnc0011** [comment]
En un inicio, la salida podría ser un dataframe de la pinta:

- Las filas serían cada uno de los modelos de los conjuntos de datos.

- Las columnas serían las recomendaciones obtenidas, recomendaciones esperadas, medida_1, ..., medida_n.
