### ISSUE TITLE
Diseño de Código fuente

### ISSUE THREAD

**Issue by bbaruque** [rnc0011/SistemaRecomendacionTFG#30]
- Pensar la distribución de métodos en módulos / clases python
- Emplear el patrón Modelo Vista Controlador

**Comment by rnc0011** [comment]
El código fuente se va a dividir en tres paquetes:

- **Entrada**, con los ficheros EntradaLightFM y EntradaLibreriaDL que leerán los archivos de datos y generarán los dataframes. (**M**VC)

- **Modelo**, con los ficheros ModeloLightFM y ModeloLibreriaDL que generarán los modelos, los entrenará y obtendrá las medidas de calidad. (MV**C**)

- **Salida**, con los ficheros SalidaLightFM y SalidaLibreriaDL que imprimirá los resultados obtenidos por los modelos. (**M**VC)

- **GUI**, con los ficheros que en un futuro se usarán como interfaz gráfica. (M**V**C)
